### ISSUE TITLE
Using this with jqLite

### ISSUE THREAD

**Issue by RongBranovate** [archived-repos/css.js#1]
Hi @jgermade !

You may remember me from the jqlite project.
I am looking for a way to inject CSS through JS dynamically and i was wondering, can i use this library with jqlite?
And if so, can i have some examples?
How would you add this code:

``` CSS
".myClass": {
        text-indent: -9999px,
        width: 16px,
        height:16px,
        border: none,
        margin-left: 15,
        margin-right: 15,
        cursor: pointer
    }
```

and this:

``` CSS
.media-player input[type='range']::-webkit-slider-thumb
{
-webkit-appearance:none;
border: 1px solid #000000;
height:36px;
width:16px;
border-radius:3px;
background:#ffffff;
cursor:pointer;
margin-top:-14px;
box-shadow: 1px 1px 1px #000000, 0px 0px 1px #0d0d0d;
};
```

thanks in advance!
